name: 001_build_and_run_in_docker
on:
  push

jobs:
  prototype_001:
    name: Build elm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and run all kinds of tests in Docker
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: |
          cd 001_build_and_run_in_docker 
          bash run-integration-tests.sh 
